<?php

/**
 * ProcessWire Home Process Replace
 *
 * Author: Diogo Oliveira
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2012 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessHomeReplace extends Process {

  static public function getModuleInfo() {
		return array(
			'title' => __('Replace Admin Home', __FILE__), // getModuleInfo title 
			'summary' => __('Replaces the Admin Home process to allow to choose the default admin page.', __FILE__), // getModuleInfo summary
			'version' => 100,
			'author' => 'Diogo Oliveira',
			'permission' => 'page-view', 
			'permanent' => true,
			);
	}

	public function ___execute() {
   		$this->session->redirect($this->page->child->url); 
	}	

}
