<?php

/**
 * ProcessWire Home Process Replace
 *
 * Author: Diogo Oliveira
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2012 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessHomeReplace extends Process implements ConfigurableModule {

	static public function getModuleInfo() {
		return array(
			'title' => __('Replace Admin Home', __FILE__), // getModuleInfo title 
			'summary' => __('Replaces the Admin Home process to allow to choose the default admin page.', __FILE__), // getModuleInfo summary
			'version' => 102,
			'author' => 'Diogo Oliveira',
			'permission' => 'page-view', 
			'permanent' => true,
		);
	}

	// redirect to the chosen page
	public function ___execute() {
		$data = wire('modules')->getModuleConfigData($this); 
		
		// load the firstPage via ID
		$firstPage = $this->pages->get($data['firstpage']);
		
		// fallback if user don't have permission or site doesn't exists anymore
		if($firstPage instanceof NullPage) {
			$firstPage = $this->pages->get('name=page,parent='.$this->config->adminRootPageID);
		}
		
   		$this->session->redirect($firstPage->url); 
	}	
	
	// enables to chose a admin page
	public static function getModuleConfigInputfields(array $data) {
		
		$inputfields = new InputfieldWrapper(); 

		$field = wire('modules')->get('InputfieldPageListSelect');
		$field->name = 'firstpage';
		$field->set('parent_id', wire('config')->adminRootPageID); 
		$field->label = "Choose the new first page";
		if(isset($data['firstpage'])) $field->value = $data['firstpage'];
		$inputfields->add($field); 
		
		return $inputfields;
	}

}
